language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
cache: bundler
